apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: job-pyspark-{{ macros.datetime.now().strftime("%Y-%m-%d-%H-%M-%S") }}
  namespace: airflow-spark-ns
spec:
  timeToLiveSeconds: 120
  volumes:
    - name: "ivy"
      persistentVolumeClaim:
        claimName: ivy-pvc
  sparkConf:
    spark.jars.packages: "com.amazonaws:aws-java-sdk-bundle:1.11.874,org.apache.hadoop:hadoop-aws:3.2.0,io.delta:delta-core_2.12:1.0.0"
    spark.driver.extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true,-Divy.cache.dir=/tmp/ivy -Divy.home=/tmp/ivy"
    spark.executor.extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true"
    spark.hadoop.fs.s3a.endpoint: "s3.us-east-2.amazonaws.com"
    spark.kubernetes.allocation.batch.size: "10"
  hadoopConf:
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "julianomuniz/spark-operator:v3.1.1-hadoop3-aws"
  # imagePullPolicy -> Always, IfNotPresent, Never
  imagePullPolicy: Always
  mainApplicationFile: "s3a://jarvis-cluster-bucket/pyspark/job_processing.py"
  #arguments:
  #  - "table"
  #deps:
  #  packages:
  #    - io.delta:delta-core_2.12:0.8.0
  #  pyFiles:
  #    - local:///opt/spark/work-dir/test.py
  #    - "s3a://jarvis-cluster-bucket/pyspark/common.zip"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
    #type: OnFailure
    #onFailureRetries: 3
    #onFailureRetryInterval: 10
    #onSubmissionFailureRetries: 5
    #onSubmissionFailureRetryInterval: 20
  driver:
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
    cores: 1
    coreLimit: "1000m"
    memory: "1g"
    labels:
      version: 3.1.1
    serviceAccount: airflow-worker
    volumeMounts:
      - name: ivy
        mountPath: /tmp/ivy
  executor:
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: aws_secret_access_key
    cores: 1
    instances: 1
    coreLimit: "1000m"
    memory: "1g"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: ivy
        mountPath: /tmp/ivy