# minikube start --mount-string="/Users/jmuniz/JM/Projetos/airflow_learning/data/pgdata:/var/lib/postgresql/data/pgdata"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-db-deployment
  labels:
    app: airflowDB
    type: back-end
spec:
  selector:
    matchLabels:
      app: airflowDB
  replicas: 1
  template:
    metadata:
      name: airflowDB-pod
      labels:
        app: airflowDB
    spec:
    
      #volumes:
      #  - name: psql-pv-storage
      #    persistentVolumeClaim:
      #      claimName: db-pv-claim

      containers:

      - name: redis
        image: redis:6.2.5
        env:
          - name: REDIS_PASSWORD
            value: 'airflow'
        ports:
          - containerPort: 6379
      
      - name: postgres
        image: postgres:13.4
        env:
          - name: POSTGRES_DB
            value: 'airflow'
          - name: POSTGRES_USER
            value: 'airflow'
          - name: POSTGRES_PASSWORD
            value: 'airflow'
          - name: PGDATA
            value: '/var/lib/postgresql/data/pgdata'
        ports:
          - containerPort: 5432
        #volumeMounts:
        #  - mountPath: "/var/lib/postgresql/data/pgdata"
        #    name: psql-pv-storage
        #command:
        #  - "postgres -c listen_addresses=*"
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-db-service
spec:
  selector:
    app: airflowDB
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: psql-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/Users/jmuniz/JM/Projetos/airflow_learning/data/pgdata"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db-pv-claim
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi