apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-db
  labels:
    app: airflowDB
    type: back-end
spec:
  selector:
    matchLabels:
      app: airflowDB
  replicas: 1
  template:
    metadata:
      name: airflowDB-pod
      labels:
        app: airflowDB
    spec:
    
      containers:

      - name: redis
        image: redis:6.2.5
        ports:
          - containerPort: 6379
      
      - name: postgres
        image: postgres:13.4
        env:
          - name: POSTGRES_DB
            value: 'airflow'
          - name: POSTGRES_USER
            value: 'airflow'
          - name: POSTGRES_PASSWORD
            value: 'airflow'
          - name: PGDATA
            value: '/var/lib/postgresql/data/pgdata'
        ports:
          - containerPort: 5432
        
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: airflowDB
spec:
  selector:
    app: airflowDB
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: airflowDB
spec:
  selector:
    app: airflowDB
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
